import SwiftUI

/**
    A view that displays an article.
 
    ATOMIZER
    Developed and Designed by John Seong.
 */

struct ExploreView: View {
    @Environment(\.adaptiveSize) var adaptiveSize
    @Environment(\.colorScheme) var colorScheme
    
    @ObservedObject var articleData = ArticleViewModel()
    
    var body: some View {
        ScrollView {
            ZStack {
                Image("backgroundImage")
                    .resizable()
                    .scaledToFill()
                    .frame(height: UIScreen.main.bounds.width < 500 ? adaptiveSize.width * 0.4 : adaptiveSize.width * 0.2)
                    .clipShape(RoundedRectangle(cornerRadius: 8))
                    .brightness(-0.2)
                    .overlay(Color.black.opacity(0.4))
                
                VStack(alignment: .center) {
                    Text("Hola, amigo")
                        .font(.system(size: 28, weight: .bold))
                        .foregroundColor(.primary)
                    
                    Text("Visualize Atoms and Molecules")
                        .font(.system(size: 18, weight: .medium))
                        .foregroundColor(.secondary)
                }
                .padding(.top, adaptiveSize.width * 0.1)
                .multilineTextAlignment(.center)
            }

            .padding()
            
            LazyVGrid(columns: [GridItem(.adaptive(minimum: 150), spacing: 16)], spacing: 16) {
                ForEach(articleData.articles) { article in
                    NavigationLink(destination: ArticleDetailView(article: article)) {
                        ArticleCardView(article: article)
                    }
                    .id(article.id)
                }
            }
            .padding()
            
            Text("Developed and Designed by John Seong.\nText-based Content Generated by GPT-4.")
                .font(.caption)
                .padding(.horizontal)
                .padding(.bottom)
                .foregroundColor(Color.gray)
        }
        .padding(.horizontal)
        .navigationTitle("Explore")
    }
}

struct ExploreView_Previews: PreviewProvider {
    static var previews: some View {
        NavigationView {
            ExploreView()
        }
        .preferredColorScheme(.light)
    }
}

extension EnvironmentValues {
    var adaptiveSize: CGSize {
        get { self[AdaptiveSizeKey.self] }
        set { self[AdaptiveSizeKey.self] = newValue }
    }
}

private struct AdaptiveSizeKey: EnvironmentKey {
    static let defaultValue: CGSize = UIScreen.main.bounds.size
}
